In [1]:
%config Completer.use_jedi = False
import warnings
warnings.filterwarnings(action='ignore')
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()
import numpy as np
import pandas as pd

WARNING:tensorflow:From D:\anaconda3\envs\py36\lib\site-packages\tensorflow\python\compat\v2_compat.py:101: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term

지문을 읽고 주제 분류하기  
다음과 같은 입력 데이터를 판다스 데이터프레임으로 저장한다. 입력 데이터는 음식 관련 및 스포츠 관련 지문으로 구성되어 있다.

In [2]:
paragraph_dict_list = [
    {'paragraph': 'Dishplace is located in sunnyvale downtown there is parking around the area but it can be difficult to find during peak business hours my sisters and i came to this place for dinner on a weekday they were really busy so i highly recommended making reservations unless you have the patience to wait', 'category': 'food'},
    {'paragraph': 'Srvice can be slower during busy hours but our waiter was courteous and help gave some great entree recommendations', 'category': 'food'},
    {'paragraph': 'Portions are huge both french toast and their various omelettes are really good their french toast is probably 1.5x more than other brunch places great place to visit if you are hungry and dont want to wait 1 hour for a table', 'category': 'food'},
    {'paragraph': 'We started with apps going the chicken and waffle slides and chicken nachos the sliders were amazing and the nachos were good too maybe by themselves the nachos would have scored better but after those sliders they were up against some tough competition', 'category': 'food'},
    {'paragraph': 'The biscuits and gravy was too salty two people in my group had the gravy and all thought it was too salty my hubby ordered a side of double egg and it was served on two small plates who serves eggs to one person on separate plates we commented on that when it was delivered and even the server laughed and said she doesnt know why the kitchen does that presentation of food is important and they really missed on this one', 'category': 'food'},
    {'paragraph': 'The garlic fries were a great starter (and a happy hour special) the pancakes looked and tasted great and were a fairly generous portion', 'category': 'food'},
    {'paragraph': 'Our meal was excellent i had the pasta ai formaggi which was so rich i didnt dare eat it all although i certainly wanted to excellent flavors with a great texture contrast between the soft pasta and the crisp bread crumbs too much sauce for me but a wonderful dish', 'category': 'food'},
    {'paragraph': 'What i enjoy most about palo alto is so many restaurants have dog-friendly seating outside i had bookmarked italico from when they first opened about a 1.5 years ago and was jonesing for some pasta so time to finally knock that bookmark off', 'category': 'food'},
    {'paragraph': 'The drinks came out fairly quickly a good two to three minutes after the orders were taken i expected my iced tea to taste a bit more sweet but this was straight up green tea with ice in it not to complain of course but i was pleasantly surprised', 'category': 'food'},
    {'paragraph': 'Despite the not so good burger the service was so slow the restaurant wasnt even half full and they took very long from the moment we got seated to the time we left it was almost 2 hours we thought that it would be quick since we ordered as soon as we sat down my coworkers did seem to enjoy their beef burgers for those who eat beef however i will not be returning it is too expensive and extremely slow service', 'category': 'food'},
    
    {'paragraph': 'The four reigning major champions simona halep caroline wozniacki angelique kerber and defending us open champion sloane stephens could make a case for being the quartet most likely to succeed especially as all but stephens has also enjoyed the no1 ranking within the last 14 months as they prepare for their gruelling new york campaigns they currently hold the top four places in the ranks', 'category': 'sports'},
    {'paragraph': 'The briton was seeded nn7 here last year before a slump in form and confidence took her down to no46 after five first-round losses but there have been signs of a turnaround including a victory over a sub-par serena williams in san jose plus wins against jelena ostapenko and victoria azarenka in montreal. konta pulled out of new haven this week with illness but will hope for good things where she first scored wins in a major before her big breakthroughs to the semis in australia and wimbledon', 'category': 'sports'},
    {'paragraph': 'Stephens surged her way back from injury in stunning style to win her first major here last year—and ranked just no83 she has since proved what a big time player she is winning the miami title via four fellow major champions then reaching the final at the french open back on north american hard courts she ran to the final in montreal only just edged out by halep she has also avoided many of the big names in her quarter—except for wild card azarenka as a possible in the third round', 'category': 'sports'},
    {'paragraph': 'When it came to england chances in the world cup it would be fair to say that most fans had never been more pessimistic than they were this year after enduring years of truly dismal performances at major tournaments – culminating in the 2014 event where they failed to win any of their three group games and finished in bottom spot those results led to the resignation of manager roy hodgson', 'category': 'sports'},
    {'paragraph': 'The team that eliminated russia – croatia – also improved enormously during the tournament before it began their odds were 33/1 but they played with real flair and star players like luka modric ivan rakitic and ivan perisic showed their quality on the world stage having displayed their potential by winning all three of their group stage games croatia went on to face difficult tests like the semi-final against england', 'category': 'sports'},
    {'paragraph': 'The perseyside outfit finished in fourth place in the premier league table and without a trophy last term after having reached the champions league final before losing to real madrid', 'category': 'sports'},
    {'paragraph': 'Liverpool fc will return to premier league action on saturday lunchtime when they travel to leicester city in the top flight as they look to make it four wins in a row in the league', 'category': 'sports'},
    {'paragraph': 'Alisson signed for liverpool fc from as roma this summer and the brazilian goalkeeper has helped the reds to keep three clean sheets in their first three premier league games', 'category': 'sports'},
    {'paragraph': 'But the rankings during that run-in to new york hid some very different undercurrents for murray had struggled with a hip injury since the clay swing and had not played a match since losing his quarter-final at wimbledon and he would pull out of the us open just two days before the tournament began—too late however to promote nederer to the no2 seeding', 'category': 'sports'},
    {'paragraph': 'Then came the oh-so-familiar djokovic-nadal no-quarter-given battle for dominance in the third set there were exhilarating rallies with both chasing to the net both retrieving what looked like winning shots nadal more than once pulled off a reverse smash and had his chance to seal the tie-break but it was djokovic serving at 10-9 who dragged one decisive error from nadal for a two-sets lead', 'category': 'sports'}
]

In [3]:
df = pd.DataFrame(paragraph_dict_list)
df

                                            paragraph category
0   Dishplace is located in sunnyvale downtown the...     food
1   Srvice can be slower during busy hours but our...     food
2   Portions are huge both french toast and their ...     food
3   We started with apps going the chicken and waf...     food
4   The biscuits and gravy was too salty two peopl...     food
5   The garlic fries were a great starter (and a h...     food
6   Our meal was excellent i had the pasta ai form...     food
7   What i enjoy most about palo alto is so many r...     food
8   The drinks came out fairly quickly a good two ...     food
9   Despite the not so good burger the service was...     food
10  The four reigning major champions simona halep...   sports
11  The briton was seeded nn7 here last year befor...   sports
12  Stephens surged her way back from injury in st...   sports
13  When it came to england chances in the world c...   sports
14  The team that eliminated russia – croatia – al...   sports
15  The perseyside outfit finished in fourth place...   sports
16  Liverpool fc will return to premier league act...   sports
17  Alisson signed for liverpool fc from as roma t...   sports
18  But the rankings during that run-in to new yor...   sports
19  Then came the oh-so-familiar djokovic-nadal no...   sports

데이터 전처리  
LSTM 모델이 입력 데이터를 처리할 수 있도록 수치값으로 변경한다.  
텍스트인 입력값을 수치로 변환하기 위해 지문에 사용된 모든 단어들을 모아서 중복을 제거한 후 단어 리스트를 만든다.

In [4]:
# 중복을 제거해 지문에 사용된 단어를 모으기 위해 빈 set을 선언한다.
results = set()
# print(type(results))
# print(type(df))                                    # <class 'pandas.core.frame.DataFrame'>
# print(type(df.paragraph))                          # <class 'pandas.core.series.Series'>
# print(type(df.paragraph.str))                      # <class 'pandas.core.strings.StringMethods'>
# print(type(df.paragraph.str.lower()))              # <class 'pandas.core.series.Series'>
# print(type(df.paragraph.str.lower().str))          # <class 'pandas.core.strings.StringMethods'>
# print(type(df.paragraph.str.lower().str.split()))  # <class 'pandas.core.series.Series'>
print(df.paragraph.str.lower().str.split())

0     [dishplace, is, located, in, sunnyvale, downto...
1     [srvice, can, be, slower, during, busy, hours,...
2     [portions, are, huge, both, french, toast, and...
3     [we, started, with, apps, going, the, chicken,...
4     [the, biscuits, and, gravy, was, too, salty, t...
5     [the, garlic, fries, were, a, great, starter, ...
6     [our, meal, was, excellent, i, had, the, pasta...
7     [what, i, enjoy, most, about, palo, alto, is, ...
8     [the, drinks, came, out, fairly, quickly, a, g...
9     [despite, the, not, so, good, burger, the, ser...
10    [the, four, reigning, major, champions, simona...
11    [the, briton, was, seeded, nn7, here, last, ye...
12    [stephens, surged, her, way, back, from, injur...
13    [when, it, came, to, england, chances, in, the...
14    [the, team, that, eliminated, russia, –, croat...
15    [the, perseyside, outfit, finished, in, fourth...
16    [liverpool, fc, will, return, to, premier, lea...
17    [alisson, signed, for, liverpool, fc, from, as...
18    [but, the, rankings, during, that, run-in, to,...
19    [then, came, the, oh-so-familiar, djokovic-nad...
Name: paragraph, dtype: object

In [5]:
# 데이터 프레임의 'paragraph'열(Serires)을 모두 소문자로 변환한 후 공백을 경계로 나눠서 set에 저장한다.
df.paragraph.str.lower().str.split().apply(results.update)
print(len(results))
print(results)

537
{'downtown', 'avoided', 'case', 'bread', 'courteous', 'when', 'iced', 'minutes', 'finally', 'plus', 'double', 'enormously', 'lunchtime', 'bottom', 'having', 'french', 'burger', 'began', 'but', 'before', 'visit', 'served', 'competition', 'help', 'pancakes', 'smash', 'fair', 'bookmarked', 'within', 'san', 'days', 'defending', 'ran', 'reds', 'which', 'england', '14', 'off', 'back', '–', 'busy', 'from', 'shots', 'dish', 'players', 'extremely', 'liverpool', 'if', 'pull', 'of', 'hodgson', 'helped', 'what', 'showed', 'than', 'biscuits', 'reservations', 'against', 'reached', 'tie-break', 'fans', 'seated', 'sweet', 'formaggi', 'left', 'truly', 'came', 'probably', 'knock', 'never', 'australia', 'person', 'would', 'ago', 'want', 'no2', 'took', 'excellent', 'reigning', 'parking', 'both', 'us', 'goalkeeper', 'omelettes', 'win', 'performances', 'expected', 'oh-so-familiar', 'separate', 'waiter', 'player', 'battle', 'miami', 'swing', 'making', 'fairly', 'victory', 'despite', 'five', 'special)', 'tasted', 'played', 'even', 'long', 'hungry', 'recommendations', 'action', 'waffle', 'failed', 'face', 'after', 'beef', 'four', 'amazing', 'possible', 'garlic', 'tournaments', 'form', 'we', 'so', 'sat', 'side', 'be', 'quickly', 'began—too', 'york', 'summer', 'it', 'got', 'cup', 'certainly', 'soon', 'tough', 'for', 'improved', 'who', 'returning', 'could', 'likely', 'restaurant', 'tests', 'big', 'service', 'and', 'eliminated', 'great', 'jonesing', 'madrid', 'card', 'quarter—except', 'are', 'eat', 'half', 'recommended', 'maybe', 'scored', 'montreal.', 'enduring', 'odds', 'stephens', 'rankings', 'haven', 'top', 'much', 'contrast', 'struggled', 'huge', 'food', 'too', 'flair', 'on', 'saturday', 'the', 'entree', 'major', 'without', 'table', 'really', 'seeded', 'slower', 'thought', 'term', 'say', 'currently', 'fc', 'sheets', 'nadal', 'three', 'quarter-final', 'crumbs', 'those', 'only', 'losing', 'dinner', 'signed', 'seeding', 'simona', 'started', 'i', 'between', 'good', 'ranking', 'he', 'different', 'burgers', 'no83', 'down', 'champion', 'week', 'her', 'more', 'leicester', 'moment', 'modric', 'small', 'apps', 'located', 'wanted', 'pulled', 'open', 'important', 'sauce', 'semis', 'group', 'our', 'no46', 'highly', 'had', 'seem', 'signs', 'no-quarter-given', 'me', 'their', 'finished', 'net', 'style', 'have', 'eggs', 'also', 'some', 'over', 'seal', 'kitchen', 'laughed', 'expensive', 'a', 'world', 'last', 'alisson', 'no1', 'serena', 'undercurrents', 'jose', 'stunning', 'full', 'wozniacki', 'led', 'set', 'crisp', 'palo', 'pleasantly', 'caroline', 'keep', 'sunnyvale', 'hip', 'clay', 'server', 'his', 'djokovic-nadal', 'bit', 'know', 'brunch', 'spot', 'sisters', 'here', 'perseyside', 'exhilarating', 'being', 'peak', 'this', 'soft', 'dominance', 'flavors', 'league', 'flight', '1.5x', 'chance', 'salty', 'first', 'sub-par', 'pasta', 'croatia', 'lead', 'perisic', '(and', 'proved', 'generous', 'themselves', 'potential', 'fourth', 'edged', 'didnt', 'tea', 'pessimistic', 'then', 'serving', 'ordered', 'egg', 'two-sets', 'look', 'angelique', 'enjoyed', 'texture', 'confidence', 'breakthroughs', 'weekday', 'orders', 'travel', '10-9', 'almost', 'during', 'briton', 'trophy', 'hold', 'clean', 'slow', 'error', 'via', 'why', 'in', 'american', 'run-in', 'any', 'ice', 'reaching', 'russia', 'dismal', 'like', 'with', 'she', 'about', 'final', 'city', 'wasnt', 'champions', 'north', 'enjoy', 'gruelling', 'better', 'alto', 'wild', 'difficult', 'portion', 'dare', 'rich', 'hours', 'two', 'outside', 'other', 'green', 'up', 'wins', 'went', 'including', 'jelena', 'murray', 'make', 'bookmark', 'patience', 'quality', 'seating', 'return', 'semi-final', 'coworkers', 'resignation', 'place', 'wonderful', 'however', 'people', '2014', 'culminating', 'course', 'toast', 'real', 'match', 'years', 'around', 'gave', 'as', 'injury', 'row', 'serves', 'fries', 'ai', 'ranked', 'business', 'going', 'sliders', 'victoria', 'hope', 'where', 'missed', 'chicken', 'did', 'wimbledon', 'by', 'montreal', 'hour', 'they', 'things', 'konta', 'quick', 'very', '1', 'just', 'results', 'games', 'especially', 'fellow', 'displayed', 'plates', 'star', 'restaurants', 'starter', 'williams', 'chances', 'event', 'looked', 'one', 'team', 'is', 'djokovic', 'roy', 'srvice', 'halep', 'rakitic', 'find', 'ranks', 'will', 'most', 'round', 'unless', 'retrieving', 'losses', 'commented', 'chasing', 'ostapenko', 'illness', 'to', 'names', 'you', 'delivered', 'meal', 'dishplace', 'winning', 'gravy', 'happy', 'rallies', 'late', 'year', 'surprised', 'area', 'stage', '1.5', 'does', 'quartet', 'said', 'all', 'once', 'hubby', 'my', 'azarenka', 'tournament', 'there', 'premier', 'slides', 'since', 'that', 'out', 'doesnt', 'title', 'has', 'many', 'taste', 'new', 'complain', 'kerber', 'nn7', 'hid', 'brazilian', 'straight', 'succeed', 'third', 'time', 'outfit', 'taken', '2', 'luka', 'nederer', 'were', 'italico', 'at', 'drinks', 'first-round', 'portions', 'turnaround', 'courts', 'although', 'ivan', 'various', 'wait', 'months', 'reverse', 'dragged', 'way', 'year—and', 'opened', 'manager', 'prepare', '33/1', 'was', 'slump', 'not', 'nachos', 'surged', 'been', 'promote', 'hard', 'dont', 'roma', 'places', 'campaigns', 'can', 'decisive', 'sloane', 'dog-friendly', 'presentation'}

set에 저장된 데이터를 아래와 같은 형태의 딕셔너리로 변환한다.
{0: 'if', 1: 'of', 2: 'side', ...., 536: 'wozniacki')

In [6]:
# enumerate() 인수로 지정된 
# for index, word in enumerate(results):
#     print(index, word)
idx2word = dict(enumerate(results))
print(type(idx2word))
print(idx2word)

<class 'dict'>
{0: 'downtown', 1: 'avoided', 2: 'case', 3: 'bread', 4: 'courteous', 5: 'when', 6: 'iced', 7: 'minutes', 8: 'finally', 9: 'plus', 10: 'double', 11: 'enormously', 12: 'lunchtime', 13: 'bottom', 14: 'having', 15: 'french', 16: 'burger', 17: 'began', 18: 'but', 19: 'before', 20: 'visit', 21: 'served', 22: 'competition', 23: 'help', 24: 'pancakes', 25: 'smash', 26: 'fair', 27: 'bookmarked', 28: 'within', 29: 'san', 30: 'days', 31: 'defending', 32: 'ran', 33: 'reds', 34: 'which', 35: 'england', 36: '14', 37: 'off', 38: 'back', 39: '–', 40: 'busy', 41: 'from', 42: 'shots', 43: 'dish', 44: 'players', 45: 'extremely', 46: 'liverpool', 47: 'if', 48: 'pull', 49: 'of', 50: 'hodgson', 51: 'helped', 52: 'what', 53: 'showed', 54: 'than', 55: 'biscuits', 56: 'reservations', 57: 'against', 58: 'reached', 59: 'tie-break', 60: 'fans', 61: 'seated', 62: 'sweet', 63: 'formaggi', 64: 'left', 65: 'truly', 66: 'came', 67: 'probably', 68: 'knock', 69: 'never', 70: 'australia', 71: 'person', 72: 'would', 73: 'ago', 74: 'want', 75: 'no2', 76: 'took', 77: 'excellent', 78: 'reigning', 79: 'parking', 80: 'both', 81: 'us', 82: 'goalkeeper', 83: 'omelettes', 84: 'win', 85: 'performances', 86: 'expected', 87: 'oh-so-familiar', 88: 'separate', 89: 'waiter', 90: 'player', 91: 'battle', 92: 'miami', 93: 'swing', 94: 'making', 95: 'fairly', 96: 'victory', 97: 'despite', 98: 'five', 99: 'special)', 100: 'tasted', 101: 'played', 102: 'even', 103: 'long', 104: 'hungry', 105: 'recommendations', 106: 'action', 107: 'waffle', 108: 'failed', 109: 'face', 110: 'after', 111: 'beef', 112: 'four', 113: 'amazing', 114: 'possible', 115: 'garlic', 116: 'tournaments', 117: 'form', 118: 'we', 119: 'so', 120: 'sat', 121: 'side', 122: 'be', 123: 'quickly', 124: 'began—too', 125: 'york', 126: 'summer', 127: 'it', 128: 'got', 129: 'cup', 130: 'certainly', 131: 'soon', 132: 'tough', 133: 'for', 134: 'improved', 135: 'who', 136: 'returning', 137: 'could', 138: 'likely', 139: 'restaurant', 140: 'tests', 141: 'big', 142: 'service', 143: 'and', 144: 'eliminated', 145: 'great', 146: 'jonesing', 147: 'madrid', 148: 'card', 149: 'quarter—except', 150: 'are', 151: 'eat', 152: 'half', 153: 'recommended', 154: 'maybe', 155: 'scored', 156: 'montreal.', 157: 'enduring', 158: 'odds', 159: 'stephens', 160: 'rankings', 161: 'haven', 162: 'top', 163: 'much', 164: 'contrast', 165: 'struggled', 166: 'huge', 167: 'food', 168: 'too', 169: 'flair', 170: 'on', 171: 'saturday', 172: 'the', 173: 'entree', 174: 'major', 175: 'without', 176: 'table', 177: 'really', 178: 'seeded', 179: 'slower', 180: 'thought', 181: 'term', 182: 'say', 183: 'currently', 184: 'fc', 185: 'sheets', 186: 'nadal', 187: 'three', 188: 'quarter-final', 189: 'crumbs', 190: 'those', 191: 'only', 192: 'losing', 193: 'dinner', 194: 'signed', 195: 'seeding', 196: 'simona', 197: 'started', 198: 'i', 199: 'between', 200: 'good', 201: 'ranking', 202: 'he', 203: 'different', 204: 'burgers', 205: 'no83', 206: 'down', 207: 'champion', 208: 'week', 209: 'her', 210: 'more', 211: 'leicester', 212: 'moment', 213: 'modric', 214: 'small', 215: 'apps', 216: 'located', 217: 'wanted', 218: 'pulled', 219: 'open', 220: 'important', 221: 'sauce', 222: 'semis', 223: 'group', 224: 'our', 225: 'no46', 226: 'highly', 227: 'had', 228: 'seem', 229: 'signs', 230: 'no-quarter-given', 231: 'me', 232: 'their', 233: 'finished', 234: 'net', 235: 'style', 236: 'have', 237: 'eggs', 238: 'also', 239: 'some', 240: 'over', 241: 'seal', 242: 'kitchen', 243: 'laughed', 244: 'expensive', 245: 'a', 246: 'world', 247: 'last', 248: 'alisson', 249: 'no1', 250: 'serena', 251: 'undercurrents', 252: 'jose', 253: 'stunning', 254: 'full', 255: 'wozniacki', 256: 'led', 257: 'set', 258: 'crisp', 259: 'palo', 260: 'pleasantly', 261: 'caroline', 262: 'keep', 263: 'sunnyvale', 264: 'hip', 265: 'clay', 266: 'server', 267: 'his', 268: 'djokovic-nadal', 269: 'bit', 270: 'know', 271: 'brunch', 272: 'spot', 273: 'sisters', 274: 'here', 275: 'perseyside', 276: 'exhilarating', 277: 'being', 278: 'peak', 279: 'this', 280: 'soft', 281: 'dominance', 282: 'flavors', 283: 'league', 284: 'flight', 285: '1.5x', 286: 'chance', 287: 'salty', 288: 'first', 289: 'sub-par', 290: 'pasta', 291: 'croatia', 292: 'lead', 293: 'perisic', 294: '(and', 295: 'proved', 296: 'generous', 297: 'themselves', 298: 'potential', 299: 'fourth', 300: 'edged', 301: 'didnt', 302: 'tea', 303: 'pessimistic', 304: 'then', 305: 'serving', 306: 'ordered', 307: 'egg', 308: 'two-sets', 309: 'look', 310: 'angelique', 311: 'enjoyed', 312: 'texture', 313: 'confidence', 314: 'breakthroughs', 315: 'weekday', 316: 'orders', 317: 'travel', 318: '10-9', 319: 'almost', 320: 'during', 321: 'briton', 322: 'trophy', 323: 'hold', 324: 'clean', 325: 'slow', 326: 'error', 327: 'via', 328: 'why', 329: 'in', 330: 'american', 331: 'run-in', 332: 'any', 333: 'ice', 334: 'reaching', 335: 'russia', 336: 'dismal', 337: 'like', 338: 'with', 339: 'she', 340: 'about', 341: 'final', 342: 'city', 343: 'wasnt', 344: 'champions', 345: 'north', 346: 'enjoy', 347: 'gruelling', 348: 'better', 349: 'alto', 350: 'wild', 351: 'difficult', 352: 'portion', 353: 'dare', 354: 'rich', 355: 'hours', 356: 'two', 357: 'outside', 358: 'other', 359: 'green', 360: 'up', 361: 'wins', 362: 'went', 363: 'including', 364: 'jelena', 365: 'murray', 366: 'make', 367: 'bookmark', 368: 'patience', 369: 'quality', 370: 'seating', 371: 'return', 372: 'semi-final', 373: 'coworkers', 374: 'resignation', 375: 'place', 376: 'wonderful', 377: 'however', 378: 'people', 379: '2014', 380: 'culminating', 381: 'course', 382: 'toast', 383: 'real', 384: 'match', 385: 'years', 386: 'around', 387: 'gave', 388: 'as', 389: 'injury', 390: 'row', 391: 'serves', 392: 'fries', 393: 'ai', 394: 'ranked', 395: 'business', 396: 'going', 397: 'sliders', 398: 'victoria', 399: 'hope', 400: 'where', 401: 'missed', 402: 'chicken', 403: 'did', 404: 'wimbledon', 405: 'by', 406: 'montreal', 407: 'hour', 408: 'they', 409: 'things', 410: 'konta', 411: 'quick', 412: 'very', 413: '1', 414: 'just', 415: 'results', 416: 'games', 417: 'especially', 418: 'fellow', 419: 'displayed', 420: 'plates', 421: 'star', 422: 'restaurants', 423: 'starter', 424: 'williams', 425: 'chances', 426: 'event', 427: 'looked', 428: 'one', 429: 'team', 430: 'is', 431: 'djokovic', 432: 'roy', 433: 'srvice', 434: 'halep', 435: 'rakitic', 436: 'find', 437: 'ranks', 438: 'will', 439: 'most', 440: 'round', 441: 'unless', 442: 'retrieving', 443: 'losses', 444: 'commented', 445: 'chasing', 446: 'ostapenko', 447: 'illness', 448: 'to', 449: 'names', 450: 'you', 451: 'delivered', 452: 'meal', 453: 'dishplace', 454: 'winning', 455: 'gravy', 456: 'happy', 457: 'rallies', 458: 'late', 459: 'year', 460: 'surprised', 461: 'area', 462: 'stage', 463: '1.5', 464: 'does', 465: 'quartet', 466: 'said', 467: 'all', 468: 'once', 469: 'hubby', 470: 'my', 471: 'azarenka', 472: 'tournament', 473: 'there', 474: 'premier', 475: 'slides', 476: 'since', 477: 'that', 478: 'out', 479: 'doesnt', 480: 'title', 481: 'has', 482: 'many', 483: 'taste', 484: 'new', 485: 'complain', 486: 'kerber', 487: 'nn7', 488: 'hid', 489: 'brazilian', 490: 'straight', 491: 'succeed', 492: 'third', 493: 'time', 494: 'outfit', 495: 'taken', 496: '2', 497: 'luka', 498: 'nederer', 499: 'were', 500: 'italico', 501: 'at', 502: 'drinks', 503: 'first-round', 504: 'portions', 505: 'turnaround', 506: 'courts', 507: 'although', 508: 'ivan', 509: 'various', 510: 'wait', 511: 'months', 512: 'reverse', 513: 'dragged', 514: 'way', 515: 'year—and', 516: 'opened', 517: 'manager', 518: 'prepare', 519: '33/1', 520: 'was', 521: 'slump', 522: 'not', 523: 'nachos', 524: 'surged', 525: 'been', 526: 'promote', 527: 'hard', 528: 'dont', 529: 'roma', 530: 'places', 531: 'campaigns', 532: 'can', 533: 'decisive', 534: 'sloane', 535: 'dog-friendly', 536: 'presentation'}

{index: 'word', ...} 형태의 딕셔너리를 {'word': idx, ...} 형태의 딕셔너리로 변환한다.

In [7]:
word2idx = {value.replace('(', '').replace(')', ''): key for key, value in idx2word.items()}
print(type(word2idx))
print(word2idx)

<class 'dict'>
{'downtown': 0, 'avoided': 1, 'case': 2, 'bread': 3, 'courteous': 4, 'when': 5, 'iced': 6, 'minutes': 7, 'finally': 8, 'plus': 9, 'double': 10, 'enormously': 11, 'lunchtime': 12, 'bottom': 13, 'having': 14, 'french': 15, 'burger': 16, 'began': 17, 'but': 18, 'before': 19, 'visit': 20, 'served': 21, 'competition': 22, 'help': 23, 'pancakes': 24, 'smash': 25, 'fair': 26, 'bookmarked': 27, 'within': 28, 'san': 29, 'days': 30, 'defending': 31, 'ran': 32, 'reds': 33, 'which': 34, 'england': 35, '14': 36, 'off': 37, 'back': 38, '–': 39, 'busy': 40, 'from': 41, 'shots': 42, 'dish': 43, 'players': 44, 'extremely': 45, 'liverpool': 46, 'if': 47, 'pull': 48, 'of': 49, 'hodgson': 50, 'helped': 51, 'what': 52, 'showed': 53, 'than': 54, 'biscuits': 55, 'reservations': 56, 'against': 57, 'reached': 58, 'tie-break': 59, 'fans': 60, 'seated': 61, 'sweet': 62, 'formaggi': 63, 'left': 64, 'truly': 65, 'came': 66, 'probably': 67, 'knock': 68, 'never': 69, 'australia': 70, 'person': 71, 'would': 72, 'ago': 73, 'want': 74, 'no2': 75, 'took': 76, 'excellent': 77, 'reigning': 78, 'parking': 79, 'both': 80, 'us': 81, 'goalkeeper': 82, 'omelettes': 83, 'win': 84, 'performances': 85, 'expected': 86, 'oh-so-familiar': 87, 'separate': 88, 'waiter': 89, 'player': 90, 'battle': 91, 'miami': 92, 'swing': 93, 'making': 94, 'fairly': 95, 'victory': 96, 'despite': 97, 'five': 98, 'special': 99, 'tasted': 100, 'played': 101, 'even': 102, 'long': 103, 'hungry': 104, 'recommendations': 105, 'action': 106, 'waffle': 107, 'failed': 108, 'face': 109, 'after': 110, 'beef': 111, 'four': 112, 'amazing': 113, 'possible': 114, 'garlic': 115, 'tournaments': 116, 'form': 117, 'we': 118, 'so': 119, 'sat': 120, 'side': 121, 'be': 122, 'quickly': 123, 'began—too': 124, 'york': 125, 'summer': 126, 'it': 127, 'got': 128, 'cup': 129, 'certainly': 130, 'soon': 131, 'tough': 132, 'for': 133, 'improved': 134, 'who': 135, 'returning': 136, 'could': 137, 'likely': 138, 'restaurant': 139, 'tests': 140, 'big': 141, 'service': 142, 'and': 294, 'eliminated': 144, 'great': 145, 'jonesing': 146, 'madrid': 147, 'card': 148, 'quarter—except': 149, 'are': 150, 'eat': 151, 'half': 152, 'recommended': 153, 'maybe': 154, 'scored': 155, 'montreal.': 156, 'enduring': 157, 'odds': 158, 'stephens': 159, 'rankings': 160, 'haven': 161, 'top': 162, 'much': 163, 'contrast': 164, 'struggled': 165, 'huge': 166, 'food': 167, 'too': 168, 'flair': 169, 'on': 170, 'saturday': 171, 'the': 172, 'entree': 173, 'major': 174, 'without': 175, 'table': 176, 'really': 177, 'seeded': 178, 'slower': 179, 'thought': 180, 'term': 181, 'say': 182, 'currently': 183, 'fc': 184, 'sheets': 185, 'nadal': 186, 'three': 187, 'quarter-final': 188, 'crumbs': 189, 'those': 190, 'only': 191, 'losing': 192, 'dinner': 193, 'signed': 194, 'seeding': 195, 'simona': 196, 'started': 197, 'i': 198, 'between': 199, 'good': 200, 'ranking': 201, 'he': 202, 'different': 203, 'burgers': 204, 'no83': 205, 'down': 206, 'champion': 207, 'week': 208, 'her': 209, 'more': 210, 'leicester': 211, 'moment': 212, 'modric': 213, 'small': 214, 'apps': 215, 'located': 216, 'wanted': 217, 'pulled': 218, 'open': 219, 'important': 220, 'sauce': 221, 'semis': 222, 'group': 223, 'our': 224, 'no46': 225, 'highly': 226, 'had': 227, 'seem': 228, 'signs': 229, 'no-quarter-given': 230, 'me': 231, 'their': 232, 'finished': 233, 'net': 234, 'style': 235, 'have': 236, 'eggs': 237, 'also': 238, 'some': 239, 'over': 240, 'seal': 241, 'kitchen': 242, 'laughed': 243, 'expensive': 244, 'a': 245, 'world': 246, 'last': 247, 'alisson': 248, 'no1': 249, 'serena': 250, 'undercurrents': 251, 'jose': 252, 'stunning': 253, 'full': 254, 'wozniacki': 255, 'led': 256, 'set': 257, 'crisp': 258, 'palo': 259, 'pleasantly': 260, 'caroline': 261, 'keep': 262, 'sunnyvale': 263, 'hip': 264, 'clay': 265, 'server': 266, 'his': 267, 'djokovic-nadal': 268, 'bit': 269, 'know': 270, 'brunch': 271, 'spot': 272, 'sisters': 273, 'here': 274, 'perseyside': 275, 'exhilarating': 276, 'being': 277, 'peak': 278, 'this': 279, 'soft': 280, 'dominance': 281, 'flavors': 282, 'league': 283, 'flight': 284, '1.5x': 285, 'chance': 286, 'salty': 287, 'first': 288, 'sub-par': 289, 'pasta': 290, 'croatia': 291, 'lead': 292, 'perisic': 293, 'proved': 295, 'generous': 296, 'themselves': 297, 'potential': 298, 'fourth': 299, 'edged': 300, 'didnt': 301, 'tea': 302, 'pessimistic': 303, 'then': 304, 'serving': 305, 'ordered': 306, 'egg': 307, 'two-sets': 308, 'look': 309, 'angelique': 310, 'enjoyed': 311, 'texture': 312, 'confidence': 313, 'breakthroughs': 314, 'weekday': 315, 'orders': 316, 'travel': 317, '10-9': 318, 'almost': 319, 'during': 320, 'briton': 321, 'trophy': 322, 'hold': 323, 'clean': 324, 'slow': 325, 'error': 326, 'via': 327, 'why': 328, 'in': 329, 'american': 330, 'run-in': 331, 'any': 332, 'ice': 333, 'reaching': 334, 'russia': 335, 'dismal': 336, 'like': 337, 'with': 338, 'she': 339, 'about': 340, 'final': 341, 'city': 342, 'wasnt': 343, 'champions': 344, 'north': 345, 'enjoy': 346, 'gruelling': 347, 'better': 348, 'alto': 349, 'wild': 350, 'difficult': 351, 'portion': 352, 'dare': 353, 'rich': 354, 'hours': 355, 'two': 356, 'outside': 357, 'other': 358, 'green': 359, 'up': 360, 'wins': 361, 'went': 362, 'including': 363, 'jelena': 364, 'murray': 365, 'make': 366, 'bookmark': 367, 'patience': 368, 'quality': 369, 'seating': 370, 'return': 371, 'semi-final': 372, 'coworkers': 373, 'resignation': 374, 'place': 375, 'wonderful': 376, 'however': 377, 'people': 378, '2014': 379, 'culminating': 380, 'course': 381, 'toast': 382, 'real': 383, 'match': 384, 'years': 385, 'around': 386, 'gave': 387, 'as': 388, 'injury': 389, 'row': 390, 'serves': 391, 'fries': 392, 'ai': 393, 'ranked': 394, 'business': 395, 'going': 396, 'sliders': 397, 'victoria': 398, 'hope': 399, 'where': 400, 'missed': 401, 'chicken': 402, 'did': 403, 'wimbledon': 404, 'by': 405, 'montreal': 406, 'hour': 407, 'they': 408, 'things': 409, 'konta': 410, 'quick': 411, 'very': 412, '1': 413, 'just': 414, 'results': 415, 'games': 416, 'especially': 417, 'fellow': 418, 'displayed': 419, 'plates': 420, 'star': 421, 'restaurants': 422, 'starter': 423, 'williams': 424, 'chances': 425, 'event': 426, 'looked': 427, 'one': 428, 'team': 429, 'is': 430, 'djokovic': 431, 'roy': 432, 'srvice': 433, 'halep': 434, 'rakitic': 435, 'find': 436, 'ranks': 437, 'will': 438, 'most': 439, 'round': 440, 'unless': 441, 'retrieving': 442, 'losses': 443, 'commented': 444, 'chasing': 445, 'ostapenko': 446, 'illness': 447, 'to': 448, 'names': 449, 'you': 450, 'delivered': 451, 'meal': 452, 'dishplace': 453, 'winning': 454, 'gravy': 455, 'happy': 456, 'rallies': 457, 'late': 458, 'year': 459, 'surprised': 460, 'area': 461, 'stage': 462, '1.5': 463, 'does': 464, 'quartet': 465, 'said': 466, 'all': 467, 'once': 468, 'hubby': 469, 'my': 470, 'azarenka': 471, 'tournament': 472, 'there': 473, 'premier': 474, 'slides': 475, 'since': 476, 'that': 477, 'out': 478, 'doesnt': 479, 'title': 480, 'has': 481, 'many': 482, 'taste': 483, 'new': 484, 'complain': 485, 'kerber': 486, 'nn7': 487, 'hid': 488, 'brazilian': 489, 'straight': 490, 'succeed': 491, 'third': 492, 'time': 493, 'outfit': 494, 'taken': 495, '2': 496, 'luka': 497, 'nederer': 498, 'were': 499, 'italico': 500, 'at': 501, 'drinks': 502, 'first-round': 503, 'portions': 504, 'turnaround': 505, 'courts': 506, 'although': 507, 'ivan': 508, 'various': 509, 'wait': 510, 'months': 511, 'reverse': 512, 'dragged': 513, 'way': 514, 'year—and': 515, 'opened': 516, 'manager': 517, 'prepare': 518, '33/1': 519, 'was': 520, 'slump': 521, 'not': 522, 'nachos': 523, 'surged': 524, 'been': 525, 'promote': 526, 'hard': 527, 'dont': 528, 'roma': 529, 'places': 530, 'campaigns': 531, 'can': 532, 'decisive': 533, 'sloane': 534, 'dog-friendly': 535, 'presentation': 536}

In [8]:
print(word2idx['player'], word2idx['really'])

90 177

word2idx 딕셔너리를 활용해서 모든 지문을 수치로 변환한다.

In [9]:
# 지문을 구성하는 모든 단어를 수치로 변환하는 함수를 만든다.
def encode_paragraph(paragraph):
    pass

# 지문이 수치로 변환된 결과를 데이터프레임에 추가한다.
df['enc_paragraph'] = df.paragraph.apply(encode_paragraph)
df

# 지문을 구성하는 모든 단어를 수치로 변환하는 함수를 만든다.
def encode_paragraph(paragraph):
    words = paragraph.split()
    # print(words)
    encoded = []
    for word in words:
        encoded.append([word2idx[word.lower().replace('(', '').replace(')', '')]])
    return encoded

# 지문이 수치로 변환된 결과를 데이터프레임에 추가한다.
df['enc_paragraph'] = df.paragraph.apply(encode_paragraph)
df.head()

,paragraph,category,enc_paragraph
0,Dishplace is located in sunnyvale downtown the...,food,"[[453], [430], [216], [329], [263], [0], [473]..."
1,Srvice can be slower during busy hours but our...,food,"[[433], [532], [122], [179], [320], [40], [355..."
2,Portions are huge both french toast and their ...,food,"[[504], [150], [166], [80], [15], [382], [294]..."
3,We started with apps going the chicken and waf...,food,"[[118], [197], [338], [215], [396], [172], [40..."
4,The biscuits and gravy was too salty two peopl...,food,"[[172], [55], [294], [455], [520], [168], [287..."

분류 항목(food[1, 0], sports[0, 1])을 원-핫 인코딩으로 수치로 변환한다.

In [10]:
def encode_category(category):
    if category == 'food':
        return [1, 0]
    else:
        return [0, 1]
    
# 분류 항목이 원-핫 인코딩으로 변환된 결과를 데이터프레임에 추가한다.
df['enc_category'] = df.category.apply(encode_category)
df

,paragraph,category,enc_paragraph,enc_category
0,Dishplace is located in sunnyvale downtown the...,food,"[[453], [430], [216], [329], [263], [0], [473]...","[1, 0]"
1,Srvice can be slower during busy hours but our...,food,"[[433], [532], [122], [179], [320], [40], [355...","[1, 0]"
2,Portions are huge both french toast and their ...,food,"[[504], [150], [166], [80], [15], [382], [294]...","[1, 0]"
3,We started with apps going the chicken and waf...,food,"[[118], [197], [338], [215], [396], [172], [40...","[1, 0]"
4,The biscuits and gravy was too salty two peopl...,food,"[[172], [55], [294], [455], [520], [168], [287...","[1, 0]"
5,The garlic fries were a great starter (and a h...,food,"[[172], [115], [392], [499], [245], [145], [42...","[1, 0]"
6,Our meal was excellent i had the pasta ai form...,food,"[[224], [452], [520], [77], [198], [227], [172...","[1, 0]"
7,What i enjoy most about palo alto is so many r...,food,"[[52], [198], [346], [439], [340], [259], [349...","[1, 0]"
8,The drinks came out fairly quickly a good two ...,food,"[[172], [502], [66], [478], [95], [123], [245]...","[1, 0]"
9,Despite the not so good burger the service was...,food,"[[97], [172], [522], [119], [200], [16], [172]...","[1, 0]"
10,The four reigning major champions simona halep...,sports,"[[172], [112], [78], [174], [344], [196], [434...","[0, 1]"
11,The briton was seeded nn7 here last year befor...,sports,"[[172], [321], [520], [178], [487], [274], [24...","[0, 1]"
12,Stephens surged her way back from injury in st...,sports,"[[159], [524], [209], [514], [38], [41], [389]...","[0, 1]"
13,When it came to england chances in the world c...,sports,"[[5], [127], [66], [448], [35], [425], [329], ...","[0, 1]"
14,The team that eliminated russia – croatia – al...,sports,"[[172], [429], [477], [144], [335], [39], [291...","[0, 1]"
15,The perseyside outfit finished in fourth place...,sports,"[[172], [275], [494], [233], [329], [299], [37...","[0, 1]"
16,Liverpool fc will return to premier league act...,sports,"[[46], [184], [438], [371], [448], [474], [283...","[0, 1]"
17,Alisson signed for liverpool fc from as roma t...,sports,"[[248], [194], [133], [46], [184], [41], [388]...","[0, 1]"
18,But the rankings during that run-in to new yor...,sports,"[[18], [172], [160], [320], [477], [331], [448...","[0, 1]"
19,Then came the oh-so-familiar djokovic-nadal no...,sports,"[[304], [66], [172], [87], [268], [230], [91],...","[0, 1]"

Dynamic RNN은 입력값의 다양한 길이를 고려하여 결과값을 출력하므로 Dynamic RNN이 각 입력값의 실제 길이(단어 개수)를 알 수 있도록 각 지문별 단어 개수를 계산해둔다.

In [11]:
# 지문을 구성하는 단어의 개수를 세는 함수를 만든다.
def word_cnt(paragraph):
    return len(paragraph.split())

# 지문을 구성하는 단어의 개수를 데이터프레임에 추가한다.
df['seq_length'] = df.paragraph.apply(word_cnt)
df

,paragraph,category,enc_paragraph,enc_category,seq_length
0,Dishplace is located in sunnyvale downtown the...,food,"[[453], [430], [216], [329], [263], [0], [473]...","[1, 0]",53
1,Srvice can be slower during busy hours but our...,food,"[[433], [532], [122], [179], [320], [40], [355...","[1, 0]",19
2,Portions are huge both french toast and their ...,food,"[[504], [150], [166], [80], [15], [382], [294]...","[1, 0]",42
3,We started with apps going the chicken and waf...,food,"[[118], [197], [338], [215], [396], [172], [40...","[1, 0]",43
4,The biscuits and gravy was too salty two peopl...,food,"[[172], [55], [294], [455], [520], [168], [287...","[1, 0]",82
5,The garlic fries were a great starter (and a h...,food,"[[172], [115], [392], [499], [245], [145], [42...","[1, 0]",24
6,Our meal was excellent i had the pasta ai form...,food,"[[224], [452], [520], [77], [198], [227], [172...","[1, 0]",50
7,What i enjoy most about palo alto is so many r...,food,"[[52], [198], [346], [439], [340], [259], [349...","[1, 0]",43
8,The drinks came out fairly quickly a good two ...,food,"[[172], [502], [66], [478], [95], [123], [245]...","[1, 0]",49
9,Despite the not so good burger the service was...,food,"[[97], [172], [522], [119], [200], [16], [172]...","[1, 0]",82
10,The four reigning major champions simona halep...,sports,"[[172], [112], [78], [174], [344], [196], [434...","[0, 1]",65
11,The briton was seeded nn7 here last year befor...,sports,"[[172], [321], [520], [178], [487], [274], [24...","[0, 1]",88
12,Stephens surged her way back from injury in st...,sports,"[[159], [524], [209], [514], [38], [41], [389]...","[0, 1]",91
13,When it came to england chances in the world c...,sports,"[[5], [127], [66], [448], [35], [425], [329], ...","[0, 1]",71
14,The team that eliminated russia – croatia – al...,sports,"[[172], [429], [477], [144], [335], [39], [291...","[0, 1]",70
15,The perseyside outfit finished in fourth place...,sports,"[[172], [275], [494], [233], [329], [299], [37...","[0, 1]",30
16,Liverpool fc will return to premier league act...,sports,"[[46], [184], [438], [371], [448], [474], [283...","[0, 1]",35
17,Alisson signed for liverpool fc from as roma t...,sports,"[[248], [194], [133], [46], [184], [41], [388]...","[0, 1]",30
18,But the rankings during that run-in to new yor...,sports,"[[18], [172], [160], [320], [477], [331], [448...","[0, 1]",63
19,Then came the oh-so-familiar djokovic-nadal no...,sports,"[[304], [66], [172], [87], [268], [230], [91],...","[0, 1]",65

텐서플로우의 RNN은 항상 같은 길이의 시쿼스를 받아야 한다.  
길이가 작은 입력 시퀀스는 패딩을 추가적으로 넣어 모든 시퀀스의 길이를 동일하게 설정한다.  
패딩이 RNN 계산에 영향을 끼치지 않도록 Dynamic RNN은 패딩 이전의 입력 시퀀스의 실제 길이를 파라미터로 받아 상태값 계산시 패딩을 제외시킨다.

In [12]:
# 최고로 긴 지문의 단어 수를 구한 수 모든 지문에 패딩을 집어넣어 최고로 긴 지문과 동일한 길이를 갖도록 만들기 위해 최고로 긴
# 지문의 단어수를 계산한다.
max_word_cnt = 0
# for row in df['paragraph']:
    # if len(row.split()) > max_word_cnt:
        # max_word_cnt = len(row.split())
# for seq in df['seq_length']:
    # if seq > max_word_cnt:
        # max_word_cnt = seq
max_word_cnt = df.seq_length.max()
print(max_word_cnt)

91

In [13]:
# 모든 지문에 패딩을 집어넣어 최고로 긴 문장과 동일한 길이를 갖게하는 함수를 만든다.
def sequence_padding(enc_paragraph):
    seq_length = len(enc_paragraph)
    for i in range(seq_length, max_word_cnt):
        enc_paragraph.append([-1])
    return enc_paragraph

# 모든 지문에 패딩이 적용된 결과를 데이터프레임에 적용한다.
df['enc_paragraph'] = df.enc_paragraph.apply(sequence_padding)
print(df['enc_paragraph'][1])
print(df['enc_paragraph'][12])

[[433], [532], [122], [179], [320], [40], [355], [18], [224], [89], [520], [4], [294], [23], [387], [239], [145], [173], [105], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1], [-1]]
[[159], [524], [209], [514], [38], [41], [389], [329], [253], [235], [448], [84], [209], [288], [174], [274], [247], [515], [394], [414], [205], [339], [481], [476], [295], [52], [245], [141], [493], [90], [339], [430], [454], [172], [92], [480], [327], [112], [418], [174], [344], [304], [334], [172], [341], [501], [172], [15], [219], [38], [170], [345], [330], [527], [506], [339], [32], [448], [172], [341], [329], [406], [191], [414], [300], [478], [405], [434], [339], [481], [238], [1], [482], [49], [172], [141], [449], [329], [209], [149], [133], [350], [148], [471], [388], [245], [114], [329], [172], [492], [440]]

In [14]:
enc_paragraph = np.array(df.enc_paragraph.tolist()) # 입력값
# print(type(df.enc_paragraph))
# print(type(df.enc_paragraph.tolist()))
# print(type(enc_paragraph))
enc_category = np.array(df.enc_category.tolist()) # 실제값
seq_length = np.array(df.seq_length.tolist()) # Dynamin RNN sequence_length 파라미터 값

train_X = enc_paragraph
print(train_X.shape)
train_Y = enc_category
print(train_Y.shape)

(20, 91, 1)
(20, 2)

텐서플로우로 지문을 읽고 주제를 분류하는 모델을 구현한다.
<img src='./data/LSTM3.png'>

문맥 벡터(contextualized vector) 생성 단계  
인덱스를 임베딩으로 변환한다. 임베딩은 학습 과정을 통해 단어 유사도를 포함하게 되어 문맥 벡터를 생헝하는데 도움을 준다.  
인간의 언어(자연어)는 수치화되어있지 않은 데이터이기 때문에 머신러닝, 딥러링 기법을 바로 사용할 수 없다. 그래서 자연어 처리에서 특징을 추출해 수치화를 해줘야 하는데 이때 사용하는 것이 '언어의 벡터화'이다. 이런 벡터화 과정을 Word Embedding이라고 한다.  
LSTM에 임베딩된 시쿼스를 입력해서 최종 상태값을 출력한다. 이 최종 상태값이 문맥 벡터이다.

주제(food, sports) 분류 단계  
문맥 벡터를 덴즈 레이어에 입력하고 출력값을 노드가 2개인 덴즈 레이어에 입력한 후 노드가 2개인 덴즈 레이어의 출력값을 소프트맥스에 입력시켜 food, sports에 대한 예측값을 구한다.

모델을 구현한다.

In [15]:
# 초기화
tf.set_random_seed(35)
# 학습율과 학습 횟수를 설정한다.
learning_rate = 0.001
n_epoch = 300

# 입력값과 출력값을 저장할 플레이스홀더를 만든다.
# 입력값은 단어들의 인덱스이며 그 길이는 지문을 구성하는 단어의 최대 개수(91, max_word_cnt)이다.
X = tf.placeholder(dtype=tf.float32, shape=[None, max_word_cnt, 1]) # (20, 91, 1)
y = tf.placeholder(dtype=tf.int32, shape=[None, 2]) # (20, 2)

# 워드 임베딩 레이어, 임베딩 레이어는 인덱스를 받아 5차원 벡터의 임베딩을 출력한다.
# tf.layers.dense()는 densely-connect layer 즉, '완전연결계층'을 만들어준다.
embedding = tf.layers.dense(X, 5)
# LSTM 셀은 64차원 벡터의 생성값을 출력한다.
cell = tf.nn.rnn_cell.LSTMCell(num_units=64)

# 출력값과 상태값을 저장한다. 상태값은 문맥 벡터로 사용되며 dense layer의 입력값이 된다.
output, state = tf.nn.dynamic_rnn(cell, embedding, dtype=tf.float32, sequence_length=seq_length)

# 주제 분류는 두 개의 덴즈 레이어를 사용한다.
# 첫 번째 덴즈 레이어는 32개 노드를 가지고 있고 두 번째 덴즈 레이어는 2개의 노드를 가지고 있으며 이 2개의 노드가 소프트맥스의
# 입력으로 들어간다.
dense_layer = tf.layers.dense(state.h, 32)
# logits는 food, sports를 원-핫 인코딩으로 구분하기 위해서 2차원 벡터로 구성한다.
logits = tf.layers.dense(dense_layer, 2)

# 손실 함수 - 크로스 엔트로피
cross_entropy = tf.nn.softmax_cross_entropy_with_logits_v2(labels=y, logits=logits)
loss = tf.reduce_mean(cross_entropy)

# Adam 옵티마이저
optimizer = tf.train.AdamOptimizer(learning_rate=learning_rate).minimize(loss)

WARNING:tensorflow:From <ipython-input-15-98cf2050816a>:19: dynamic_rnn (from tensorflow.python.ops.rnn) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `keras.layers.RNN(cell)`, which is equivalent to this API
WARNING:tensorflow:From D:\anaconda3\envs\py36\lib\site-packages\keras\layers\legacy_rnn\rnn_cell_impl.py:979: calling Zeros.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor

모델 요약

In [16]:
# 문맥 벡터 생성
# 입력값은 단어들의 인덱스이며 그 길이는 항상 91이다.
print(X) # Tensor("Placeholder:0", shape=(?, 91, 1), dtype=float32)
# 임베딩 레이어는 인덱스를 받아 5차원 벡터의 임베딩을 출력한다.
print(embedding) # Tensor("dense/BiasAdd:0", shape=(?, 91, 5), dtype=float32)
# LSTM 셀은 64차원 벡터의 상태값을 출력한다.
print(state.h) # Tensor("rnn/while/Exit_4:0", shape=(?, 64), dtype=float32)

# 문맥 벡터를 사용해 지문의 주제 분류하기, 주제 분류는 두 개의 덴즈 레이어를 사용한다.
# 첫 번째 덴즈 레이어는 32개의 노드를 가지고 있다.
print(dense_layer) # Tensor("dense_1/BiasAdd:0", shape=(?, 32), dtype=float32)
# 두 번재 덴즈 레이어는 2개의 노드를 가지고 있으며, 이 2개의 노드는 소프트맥스의 입력값으로 들어간다.
print(logits) # Tensor("dense_2/BiasAdd:0", shape=(?, 2), dtype=float32)

Tensor("Placeholder:0", shape=(?, 91, 1), dtype=float32)
Tensor("dense/BiasAdd:0", shape=(?, 91, 5), dtype=float32)
Tensor("rnn/while/Exit_4:0", shape=(?, 64), dtype=float32)
Tensor("dense_1/BiasAdd:0", shape=(?, 32), dtype=float32)
Tensor("dense_2/BiasAdd:0", shape=(?, 2), dtype=float32)

학습 시킨다.

In [17]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for epoch in range(n_epoch + 1):
        sess.run(optimizer, feed_dict={X: train_X, y: train_Y})
        train_loss = sess.run(loss, feed_dict={X: train_X, y: train_Y})
        
        if epoch % 50 == 0:
            predict = tf.nn.softmax(logits)
            # 정확도 계산
            correct_prediction = tf.equal(tf.argmax(predict, 1), tf.argmax(y, 1))
            accuracy = tf.reduce_mean(tf.cast(correct_prediction, 'float'))
            cur_acc = accuracy.eval(feed_dict={X: train_X, y: train_Y})
            print('epoch: {:3d}, loss: {:6.4f}, acc: {:6.4f}'.format(epoch, train_loss, cur_acc))

epoch:   0, loss: 0.6963, acc: 0.5500
epoch:  50, loss: 0.3696, acc: 0.8500
epoch: 100, loss: 0.0419, acc: 1.0000
epoch: 150, loss: 0.0005, acc: 1.0000
epoch: 200, loss: 0.0002, acc: 1.0000
epoch: 250, loss: 0.0002, acc: 1.0000
epoch: 300, loss: 0.0001, acc: 1.0000